package project.event.io.app.core.user.exception

class UserNotFoundException : RuntimeException()
